package model;

// Generated 2015-8-29 23:45:21 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * BorrowrecordId generated by hbm2java
 */
public class BorrowrecordId implements java.io.Serializable {

	private String borrowerName;
	private String tele;
	private Integer itemId;
	private int itemName;
	private int itemInfo;
	private int number;
	private Date borrowDate;
	private Date returnDate;

	public BorrowrecordId() {
	}

	public BorrowrecordId(String borrowerName, String tele, int itemName,
			int itemInfo, int number, Date borrowDate, Date returnDate) {
		this.borrowerName = borrowerName;
		this.tele = tele;
		this.itemName = itemName;
		this.itemInfo = itemInfo;
		this.number = number;
		this.borrowDate = borrowDate;
		this.returnDate = returnDate;
	}

	public BorrowrecordId(String borrowerName, String tele, Integer itemId,
			int itemName, int itemInfo, int number, Date borrowDate,
			Date returnDate) {
		this.borrowerName = borrowerName;
		this.tele = tele;
		this.itemId = itemId;
		this.itemName = itemName;
		this.itemInfo = itemInfo;
		this.number = number;
		this.borrowDate = borrowDate;
		this.returnDate = returnDate;
	}

	public String getBorrowerName() {
		return this.borrowerName;
	}

	public void setBorrowerName(String borrowerName) {
		this.borrowerName = borrowerName;
	}

	public String getTele() {
		return this.tele;
	}

	public void setTele(String tele) {
		this.tele = tele;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public int getItemName() {
		return this.itemName;
	}

	public void setItemName(int itemName) {
		this.itemName = itemName;
	}

	public int getItemInfo() {
		return this.itemInfo;
	}

	public void setItemInfo(int itemInfo) {
		this.itemInfo = itemInfo;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public Date getBorrowDate() {
		return this.borrowDate;
	}

	public void setBorrowDate(Date borrowDate) {
		this.borrowDate = borrowDate;
	}

	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BorrowrecordId))
			return false;
		BorrowrecordId castOther = (BorrowrecordId) other;

		return ((this.getBorrowerName() == castOther.getBorrowerName()) || (this
				.getBorrowerName() != null
				&& castOther.getBorrowerName() != null && this
				.getBorrowerName().equals(castOther.getBorrowerName())))
				&& ((this.getTele() == castOther.getTele()) || (this.getTele() != null
						&& castOther.getTele() != null && this.getTele()
						.equals(castOther.getTele())))
				&& ((this.getItemId() == castOther.getItemId()) || (this
						.getItemId() != null && castOther.getItemId() != null && this
						.getItemId().equals(castOther.getItemId())))
				&& (this.getItemName() == castOther.getItemName())
				&& (this.getItemInfo() == castOther.getItemInfo())
				&& (this.getNumber() == castOther.getNumber())
				&& ((this.getBorrowDate() == castOther.getBorrowDate()) || (this
						.getBorrowDate() != null
						&& castOther.getBorrowDate() != null && this
						.getBorrowDate().equals(castOther.getBorrowDate())))
				&& ((this.getReturnDate() == castOther.getReturnDate()) || (this
						.getReturnDate() != null
						&& castOther.getReturnDate() != null && this
						.getReturnDate().equals(castOther.getReturnDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getBorrowerName() == null ? 0 : this.getBorrowerName()
						.hashCode());
		result = 37 * result
				+ (getTele() == null ? 0 : this.getTele().hashCode());
		result = 37 * result
				+ (getItemId() == null ? 0 : this.getItemId().hashCode());
		result = 37 * result + this.getItemName();
		result = 37 * result + this.getItemInfo();
		result = 37 * result + this.getNumber();
		result = 37
				* result
				+ (getBorrowDate() == null ? 0 : this.getBorrowDate()
						.hashCode());
		result = 37
				* result
				+ (getReturnDate() == null ? 0 : this.getReturnDate()
						.hashCode());
		return result;
	}

}
