package model;

// Generated 2015-8-29 23:45:21 by Hibernate Tools 4.3.1

/**
 * Borrowrecord generated by hbm2java
 */
public class Borrowrecord implements java.io.Serializable {

	private BorrowrecordId id;

	public Borrowrecord() {
	}

	public Borrowrecord(BorrowrecordId id) {
		this.id = id;
	}

	public BorrowrecordId getId() {
		return this.id;
	}

	public void setId(BorrowrecordId id) {
		this.id = id;
	}

}
