package model;

// Generated 2015-8-29 23:45:21 by Hibernate Tools 4.3.1

/**
 * Iteminfo generated by hbm2java
 */
public class Iteminfo implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private String type;
	private int count;

	public Iteminfo() {
	}

	public Iteminfo(String name, String type, int count) {
		this.name = name;
		this.type = type;
		this.count = count;
	}

	public Iteminfo(String name, String description, String type, int count) {
		this.name = name;
		this.description = description;
		this.type = type;
		this.count = count;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
